DjangoMovieDatabase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # Django admin
    path('admin/', admin.site.urls),

    # Local apps
    path('', include('users.urls')),
    path('', include('movies.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import AccountPageView, signup_login_handler
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', signup_login_handler, name='login'),
    path('signup/', signup_login_handler, name='signup'),
    path('account/', AccountPageView.as_view(), name='account'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from django.utils import timezone
from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    class GenderType(models.TextChoices):
        NONE = "", "----"
        FEMALE = "F", _("Female")
        MALE = "M", _("Male")
        X_GENDER = "X", _("X")

    email = models.EmailField(_('email_address'), max_length=100, unique=True)
    date_of_birth = models.DateField()
    gender = models.CharField(choices=GenderType.choices, default=GenderType.NONE, max_length=4)
    country = CountryField()
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth', 'gender', 'country']

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.forms.widgets import NumberInput
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    date_of_birth = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))

    class Meta:
        model = CustomUser
        fields = ('email', 'date_of_birth', 'gender', 'country')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'gender', 'country')


class CustomAuthenticationForm(AuthenticationForm):
    pass

users/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.http import HttpResponseRedirect


class AccountPageView(generic.TemplateView):
    template_name = 'users/account.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/')
        return super(AccountPageView, self).dispatch(request, *args, **kwargs)


def signup_login_handler(request):
    """
    Using FBV to handle two different form in a same page is pretty convenient than using CBV
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('home'))
    else:
        if request.method == 'POST':
            signup_form = CustomUserCreationForm()
            login_form = CustomAuthenticationForm()
            if request.POST.get('login'):
                login_form = CustomAuthenticationForm(request, data=request.POST)
                if login_form.is_valid():
                    email = login_form.cleaned_data.get('username')
                    password = login_form.cleaned_data.get('password')
                    user = authenticate(username=email, password=password)
                    if user:
                        login(request, user)
                        messages.info(request, f"You are now logged in as {email}.")
                        return HttpResponseRedirect(reverse_lazy('home'))
                    # else:
                    #     messages.error(request, "Invalid login details given.")
                    #     return HttpResponseRedirect(reverse_lazy('login'))
                else:
                    messages.error(request, "Invalid login details given.")
                    return HttpResponseRedirect(reverse_lazy('login'))

            elif request.POST.get('signup'):
                signup_form = CustomUserCreationForm(request.POST)
                if signup_form.is_valid():
                    user = signup_form.save()
                    messages.success(request, f'Account created for {user.email}.\n Now, you can login!')
                    return HttpResponseRedirect(reverse_lazy('login'))

        else:
            signup_form = CustomUserCreationForm()
            login_form = CustomAuthenticationForm()

        return render(request, 'users/signup_login.html', {
            'signup_form': signup_form,
            'login_form': login_form,
        })

templates/users/account.html
{% extends '_base.html' %}
{% block content %}
<h1>My Account</h1>
{% endblock content %}

templates/users/signup_login.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    {% if 'login' in request.get_full_path %}
        Login
    {% else %}
        Signup
    {% endif %}
{% endblock title %}

{% block statichead %}
<!-- CSS -->
<link rel="stylesheet" href="{% static 'users/css/login.css' %}">
{% endblock statichead %}

{% block navbar %}
{% endblock navbar %}

{% block content %}
<div class="">
    <div class="row">
        <div class="col-md-6 mx-auto p-0">
            <div class="card">
                <div class="login-box">
                    <div class="login-snip">
                        {% if 'login' in request.get_full_path %}
                            <input id="tab-1" type="radio" name="tab" class="sign-in" checked>
                        {% else %}
                            <input id="tab-1" type="radio" name="tab" class="sign-in">
                        {% endif %}
                        <label for="tab-1" class="tab">Login</label>
                        {% if 'login' in request.get_full_path %}
                            <input id="tab-2" type="radio" name="tab" class="sign-up">
                        {% else %}
                            <input id="tab-2" type="radio" name="tab" class="sign-up" checked>
                        {% endif %}
                        <label for="tab-2" class="tab">Sign Up</label>
                        <div class="login-space">
                            <div class="login">
                                <form method="post">
                                    {% csrf_token %}
                                    {% if login_form.non_field_errors %}
                                        <div class="alert alert-error">
                                            {% for error in login_form.non_field_errors %}
                                                <p style="color: red">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                    {% if messages %}
                                        {% for message in messages %}
                                            {% if 'success' in message.tags %}
                                                <h5 style="color: lawngreen">{{ message }}</h5>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                    <div class="group">
                                        <label for="id_username" class="label">Email Address</label>
                                        <input type="text" class="input" name="username" autofocus="" autocapitalize="none" autocomplete="email" maxlength="100" required="" id="id_username" placeholder="Enter your email address">
                                    </div>
                                    <div class="group">
                                        <label for="id_password" class="label">Password</label>
                                        <input type="password" class="input" name="password" autocomplete="current-password" required="" id="id_password" placeholder="Enter your password">
                                    </div>
                                    <div class="group">
                                        <input type="submit" name="login" class="button" value="Sign In">
                                    </div>
                                </form>
                                <div class="hr"></div>
                                <div class="foot"> <a href="#">Forgot Password?</a> </div>
                            </div>
                            <div class="sign-up-form">
                                <form method="post">
                                    {% csrf_token %}
                                     {% if signup_form.non_field_errors %}
                                        <div class="alert alert-error">
                                            {% for error in signup_form.non_field_errors %}
                                                <h6 style="color: red">{{ error }}</h6>
                                            {% endfor %}
                                        </div>
                                    {% endif %}

                                    {% for field in signup_form %}
                                        {% for error in field.errors %}
                                            <h6 style="color: red">{{ error }}</h6>
                                        {% endfor %}
                                    {% endfor %}

                                    <div class="group">
                                        <label for="id_email" class="label">Email Address</label>
                                        <input type="email" name="email" class="input" maxlength="100" autofocus="" required="" id="id_email" placeholder="Enter your email address">
                                    </div>
                                    <div class="group">
                                        <label class="label" for="{{ signup_form.date_of_birth.id_for_label }}">Date of birth:</label>
                                        <input class="input" type="date" name="{{ signup_form.date_of_birth.name }}" required="" id="{{ signup_form.date_of_birth.id_for_label }}">
                                    </div>
                                    <div class="group">
                                        <label for="{{ signup_form.gender.id_for_label }}" class="label">{{ signup_form.gender.name }}</label>
                                        <select class="select" name="{{ signup_form.gender.name }}" required="" id="{{ signup_form.gender.id_for_label }}">
                                            {% for pk,value in signup_form.gender.field.choices %}
                                                <option value="{{ pk }}">{{ value }}</option>
                                            {% endfor %}
                                        </select>
                                        {% if signup_form.gender.errors %}
                                            <ol>
                                            {% for error in signup_form.gender.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                    </div>
                                    <div class="group">
                                        <label for="{{ signup_form.country.name }}" class="label">{{ signup_form.country.name }}</label>
                                        <select name="{{ signup_form.country.name }}" required="" id="{{ signup_form.country.name }}">
                                            {% for pk,value in signup_form.country.field.choices %}
                                                <option value="{{ pk }}">{{ value }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="group">
                                        <label for="id_password1" class="label">Password</label>
                                        <input type="password" name="password1" class="input" data-type="password" autocomplete="new-password" required="" id="id_password1" placeholder="Create your password">
                                    </div>
                                    <div class="group">
                                        <label for="id_password2" class="label">Repeat Password</label>
                                        <input type="password" name="password2" class="input" data-type="password" autocomplete="new-password" required="" id="id_password2" placeholder="Repeat your password">
                                    </div>
                                    <div class="group">
                                        <input type="submit" name="signup" class="button" value="Sign Up">
                                    </div>
                                </form>
                                <div class="hr"></div>
                                <div class="foot"> <label for="tab-1">Already Member?</label> </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}